---
- 
  name: Install the mysql
  host: 0.0.0.0
  tasks:
    - name: mysql
      service: 
         name: httpd 
         state: present
   
    - name: Install
      yum: name={{ item}} state=latest
      with_items:
        - python
        - python setuptools
